Vul_container_scanning:
  stage: test
  image:
    name: alpine:3.11
  variables:
    # Override the GIT_STRATEGY variable in your `.gitlab-ci.yml` file and set it to `fetch` if you want to provide a `clair-whitelist.yml`
    # file. See https://docs.gitlab.com/ee/user/application_security/container_scanning/index.html#overriding-the-container-scanning-template
    # for details
    GIT_STRATEGY: none
    IMAGE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
  allow_failure: true
  before_script:
    - export VUL_VERSION=${VUL_VERSION:-v0.19.2}
    - apk add --no-cache curl docker-cli
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - curl -sfL https://raw.githubusercontent.com/khulnasoft-lab/vul/main/contrib/install.sh | sh -s -- -b /usr/local/bin ${VUL_VERSION}
    - curl -sSL -o /tmp/vul-gitlab.tpl https://github.com/khulnasoft-lab/vul/raw/${VUL_VERSION}/contrib/gitlab.tpl
  script:
    - vul --exit-code 0 --cache-dir .vulcache/ --no-progress --format template --template "@/tmp/vul-gitlab.tpl" -o gl-container-scanning-report.json $IMAGE
  cache:
    paths:
      - .vulcache/
  artifacts:
    reports:
      container_scanning: gl-container-scanning-report.json
  dependencies: []
  only:
    refs:
      - branches
