{{- if not .Values.vul.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vul.fullname" . }}
  labels:
{{ include "vul.labels" . | indent 4 }}
type: Opaque
data:
  GITHUB_TOKEN: {{ .Values.vul.gitHubToken | default "" | b64enc | quote }}
  VUL_TOKEN: {{ .Values.vul.serverToken | default "" | b64enc | quote }}
{{- if not .Values.vul.registryCredentialsExistingSecret }}
  VUL_USERNAME: {{ .Values.vul.registryUsername | default "" | b64enc | quote }}
  VUL_PASSWORD: {{ .Values.vul.registryPassword | default "" | b64enc | quote }}
{{- end -}}
{{- end }}
