apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vul.fullname" . }}
  labels:
{{ include "vul.labels" . | indent 4 }}
type: Opaque
data:
  gitHubToken: {{ .Values.vul.gitHubToken | default "" | b64enc | quote }}
