apiVersion: v1
kind: Service
metadata:
  name: {{ include "vul.fullname" . }}
  labels:
{{ include "vul.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app.kubernetes.io/name: {{ include "vul.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: vul-http
      protocol: TCP
      port: {{ .Values.service.port | default 4954 }}
      targetPort: {{ .Values.service.port | default 4954 }}
  sessionAffinity: ClientIP
