// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package operation

import (
	db2 "github.com/khulnasoft-lab/vul-db/pkg/db"
	"github.com/khulnasoft-lab/vul/pkg/db"
	"github.com/khulnasoft-lab/vul/pkg/github"
	"github.com/khulnasoft-lab/vul/pkg/indicator"
	"github.com/spf13/afero"
	"k8s.io/utils/clock"
)

// Injectors from inject.go:

func initializeDBClient(cacheDir string, quiet bool) db.Client {
	config := db2.Config{}
	client := github.NewClient()
	progressBar := indicator.NewProgressBar(quiet)
	realClock := clock.RealClock{}
	fs := afero.NewOsFs()
	metadata := db.NewMetadata(fs, cacheDir)
	dbClient := db.NewClient(config, client, progressBar, realClock, metadata)
	return dbClient
}
